@host = http://localhost:5007

### Get Users v1
GET {{host}}/api/v1/users

### Get Users v2
GET {{host}}/api/v2/users

### Delete User (version-neutral)
DELETE {{host}}/api/users/1

### Get Scores v1
GET {{host}}/api/v1/scores

### Get Scores v2
GET {{host}}/api/v2/scores

### OpenAPI v1
GET {{host}}/openapi/v1.json

### OpenAPI v2
GET {{host}}/openapi/v2.json

### Swagger v1 (Swashbuckle)
GET {{host}}/swagger/v1/swagger.json

### Swagger v2 (Swashbuckle)
GET {{host}}/swagger/v2/swagger.json
